# Engine-wide options
option(KYLIE_ENABLE_LUA "Enable Lua scripting hook (stub)" OFF)
option(KYLIE_ENABLE_PYTHON "Enable Python scripting bridge (stub)" OFF)
option(KYLIE_ENABLE_RENDERER "Build OpenGL renderer (glfw/glad/imgui)" ON)
option(KYLIE_STRICT_WARNINGS "Enable strict compiler warnings" ON)
option(BUILD_PLUGINS "Build sample plugins" ON)
option(BUILD_EXAMPLES "Build example executables" ON)
option(BUILD_EDITOR "Build editor CLI" ON)
option(BUILD_SANDBOX "Build sandbox demo executable" ON)
option(BUILD_LAUNCHER "Build launcher executable" ON)
